name: PokerOdds
options:
  bundleIdPrefix: com.by123
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_STYLE: Automatic

targets:
  PokerOdds:
    type: application
    platform: iOS
    sources:
      - PokerOdds/Sources
    resources:
      - PokerOdds/Resources
    info:
      path: PokerOdds/Resources/Info.plist
      properties:
        CFBundleDisplayName: "Poker Odds"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.by123.pokerodds
