name: PokerOdds
options:
  bundleIdPrefix: com.by123
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_STYLE: Automatic

targets:
  PokerOdds:
    type: application
    platform: iOS
    sources:
      - PokerOdds/Sources
    resources:
      - PokerOdds/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.by123.pokerodds
      INFOPLIST_GENERATION_MODE: GeneratedFile
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
      INFOPLIST_KEY_CFBundleDisplayName: "Poker Odds"
